import React, { Component, PropTypes } from 'react';

import './AboutPage.scss';

export class About extends Component {

  render () {
    return (
      <div className='About'>
        <div className='row'>
          <div className='modal column small-10 small-centered  '>
            <br />
            <div className='row'>
              <div className='column small-11 small-centered'>
                <h1>About</h1>
                <hr/>
                All of the "Praktizieren" content is generated by Javascript. So if it speaks poorly about your mother, just let it go.
                <br/>
                <br/>
                The daily background image is National Geographic's photo of the day.
                <br/>
                <br/>
                This is an <a href="https://github.com/whroman/conjugate">open source project</a>.
              </div>
            </div>
            <br />
          </div>
        </div>
      </div>
    );
  }

}

export default About;
